routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');

});
Route::get('hasil','VoteController@hasil');
Route::view('about','about');
Route::resource('vote','VoteController');


Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');
Route::resource('/admin/peserta', 'PesertaController',['as'=>'admin']);
Route::resource('/admin/formatur', 'FormaturController',['as'=>'admin']);
Route::get('swal/{type}', 'HomeController@myNotification');

resources/views/about.blade.php
@extends('layouts.votelayout')
@section('content')
<div class="container">
	<div class="col-md-2"></div>
	<div class="col-md-8">
	<h3>Tentang E-Voting</h3>
	<p>Sistem E-voting atau yang dikenal dengan istilah Electronic Voting merupakan sistem pemilihan secara online. Sistem ini dikembangkan untuk mengurangi penggunaan kertas sekali pakai pada proses-proses pemilihan yang ada.</p>
	<p>Sistem E-Voting ini dikembangkan oleh <a href="https://gitlab.com/ragilpamungkas">Ragil Burhanudin Pamungkas</a> dan bersifat Open Source. Sistem E-Voting ini dapat diunduh di <a href="https://gitlab.com/ragilpamungkas">gitlab.com/ragilpamungkas.</a></p>
	<p>Pengembang menerima masukkan agar sistem E-Voting ini dapat terus berkembang serta dapat menutup bug-bug yang ada. Apabila pengguna menemukan bug, maka dapat langsung dilaporkan besrta screenshots di link <a href="https://gitlab.com/ragilpamungkas">Gitlab berikut</a> dan submit bug yang ada.</p>
	<p>Terima Kasih Telah Menggunakan Sistem E-Voting</p>
	<p>Untuk Pengguna diharapkan tetap memberikan credit link ke link <a href="https://gitlab.com/ragilpamungkas">Gitlab ini</a></p>
	<div class="col-md-4"></div>
	<div class="col-md-4"></div>
	<div class="col-md-4"><p align="center"><b>Dev.<br><br><br>Ragil Burhanudin Pamungkas</b</p>
	</div></div>
	
	<div class="col-md-8"></div>
</div>
@endsection

resources/views/formatur-detail.blade.php
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Calon Formatur</h4>
      </div>
      <div class="modal-body">
        
        <img src="https://placehold.it/150x80?text=FotoFormatur" id="foto" style="width:150px; height: 200px; text-align: center;">
        <br><br><br>

        <div class="clearfix"></div>

        <div style="text-align: left;">
          <label class="col-md-2">Nama</label><label class="col-md-10" id="nama">error</label>
          <label class="col-md-2">NIM</label><label class="col-md-10" id="nim">error</label>
          <label class="col-md-2">TTL</label><label class="col-md-10" id="ttl">error</label>
          <label class="col-md-2">Jurusan</label><label class="col-md-10" id="jurusan">error</label>
          <label class="col-md-12" style="text-align: center">Visi</label>
          <label class="col-md-2"></label><label class="col-md-8" id="visi">error</label><label class="col-md-2"></label>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="modal-footer" style="text-align: center;">
        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i>  Tutup</button>
      </div>
    </div>
  </div>
</div>

resources/views/home.blade.php
@extends('layouts.admin')
@section('content')
 <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-3 col-xs-6"></div>
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3>{{ count($formatur) }}<sup style="font-size: 20px">Orang</sup></h3>

              <p>Formatur Terdaftar</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
            <a href="{{ route('admin.formatur.index') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>{{ count($peserta) }}</h3>

              <p>Peserta Terdaftar</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
         <div class="col-lg-3 col-xs-6"></div>
      </div>
      <!-- /.row -->
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
        <div class="alert alert-danger" style="text-align: center;">
          <h3>Amanah Bukan untuk mainan !!</h3>
        </div>
        </div>
        <div class="col-lg-3"></div>
      </div>

    </section>
    <!-- /.content -->


@endsection

resources/views/landing.blade.php
@extends('layouts.votelayout')
@section('content')
<div class="container">
	<div class="col-md-3"></div>
	<div class="col-md-6">
	<h3>AMANAH BUKAN UNTUK MAINAN !!</h3>
	<br>
	<br>
	<div style="text-align: center">
	<a href="{{ url('vote') }}" class="btn btn-success">Vote</a>
	<a href="{{ url('hasil') }}" class="btn btn-info">Hasil</a>
	<a href="{{ url('about') }}" class="btn btn-warning">Tentang Kami</a>
	</div>
	<br>
	<br>
	<p>Terima Kasih Telah Menggunakan Sistem E-Voting</p>
	
	
	</div></div>
	
	<div class="col-md-3"></div>
</div>
@endsection

resources/views/my-notification.blade.php
<!DOCTYPE html>

<html>

<head>

	<title>Laravel Sweet Alert Notification</title>

	<link rel="stylesheet" href="http://demo.itsolutionstuff.com/plugin/bootstrap-3.min.css">

	<script src="http://demo.itsolutionstuff.com/plugin/jquery.js"></script>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

	<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

</head>

<body>


<h1 class="text-center">Laravel Sweet Alert Notification</h1>

@include('sweet::alert')


</body>

</html>

resources/views/tes.blade.php
@extends('layouts.votelayout')
@section('content')
<div class="container" align="center">
<h3>Hasil Pemilihan Formatur</h3>
		<script src="{{('bower_components/chart.js/Chart.js')}}"></script>
		
		<div style="width: 80%">
			<canvas id="canvas"></canvas>
		</div>
		
		<?php $no=0 ?>

		<table class="table">
			<thead>
			<tr>
				<th>#</th>
				<th>ID</th>
				<th>Nama</th>
				<th>NIM</th>
				<th>Jumlah Suara</th>
			</tr>
			</thead>
			<tbody>
			@foreach($teratas as $t)
			<tr>
				<td>{{$no+=1}}</td>
				<td>{{$t->id}}</td>
				<td>{{$t->nama}}</td>
				<td>{{$t->nim}}</td>
				<td>{{$t->jumlah}}</td>
			</tr>
			@endforeach
			</tbody>
			

		</table>
	</div>
		

	<script>
	var randomScalingFactor = function(){ return Math.round(Math.random()*100)};

	var barChartData = {
		labels : [
		@foreach($hasil as $h)
		"{{$h->nama}}",
		@endforeach],
		datasets : [
			{
				fillColor : "rgba(151,187,205,0.5)",
				strokeColor : "rgba(151,187,205,0.8)",
				highlightFill : "rgba(151,187,205,0.75)",
				highlightStroke : "rgba(151,187,205,1)",
				data : [@foreach($hasil as $h)
						{{$h->jumlah}},
						@endforeach]
			}
		]

	}
	window.onload = function(){
		var ctx = document.getElementById("canvas").getContext("2d");
		window.myBar = new Chart(ctx).Bar(barChartData, {
			responsive : true
		});
	}

	</script>
@endsection