routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');

});
Route::get('hasil','VoteController@hasil');
Route::view('about','about');
Route::resource('vote','VoteController');


Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');
Route::resource('/admin/peserta', 'PesertaController',['as'=>'admin']);
Route::resource('/admin/formatur', 'FormaturController',['as'=>'admin']);
Route::get('swal/{type}', 'HomeController@myNotification');

app/Vote.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vote extends Model
{
    protected $table = 'votes';
}

app/Http/Controllers/VoteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use App\Formatur;
use App\Peserta;
use App\Vote;
use Alert;

class VoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $arr['formatur'] = Formatur::all();
        return view('vote.index')->with($arr);            
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Vote $vote)
    {
        $user_id = $request->user_id;
        $formatur_id = $request->formatur_id;
        $cek = DB::table('votes')->where('user_id',$user_id)->count();

        
        if (DB::table('pesertas')->where('user_id',$user_id)->exists() and (count($formatur_id)==13) and ($cek == 0)) {
            foreach ($formatur_id as $id) {
                DB::table('votes')->insert(['formatur_id' => $id, 'user_id' => $user_id]);
                
            }
            alert()->success('Terima Kasih Telah Memilih ','Sukses!')->persistent('Ok');
            return back();
        }
        else
        {
            alert()->error('Periksa kembali ID peserta dan jumlah pilihan Anda, pastikan tidak kurang dan tidak lebih dari 13 ','Oops!')->persistent('Ok');
            return back();
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

   public function hasil(){
    $arr['hasil'] = DB::table('formaturs')
                ->selectRaw('formaturs.id, formaturs.nama, formaturs.nim, (select count(*) from votes where formatur_id = formaturs.id) jumlah')
                ->get();
    $arr['teratas'] = DB::table('formaturs')
                ->selectRaw('formaturs.id, formaturs.nama, formaturs.nim, (select count(*) from votes where formatur_id = formaturs.id) jumlah')
                ->orderByRaw('jumlah desc')
                ->get();
    
    
    return view('tes')->with($arr);
                   
   }
}

resources/views/vote/index.blade.php
@extends('layouts.votelayout')

@section('content')
<div class="container text-center">
  <h3>Daftar Formatur</h3><br>
  <div class="row">
    <form method="POST" action="{{route('vote.store')}}">
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      @if(count($formatur))
      <div class="jumbotron">
        <div class="form-group">
          <div class="row">
            <label>ID Peserta</label>
            <br>
            <div class="col-md-4"></div>
            <div class="col-md-4"><input type="text" name="user_id" class="form-control"></div>
            <div class="col-md-4"></div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>



      <div class="clearfix"></div>
      @foreach($formatur as $f)

      <div class="col-sm-3 col-md-3 col-lg-3">
        <label class="btn">
        <img src="{{asset('storage/formatur/'.$f->image)}}" class="img-responsive" style="height: 150px;width: 200px" alt="Image">
        <input type="checkbox" class="single-checkbox" name="formatur_id[]" value="{{ $f->id }}">
        </label>
        <br>
        <label>{{ $f->nama}}</label><br>
        <label>{{ $f->jurusan}}</label>
        <br>
        <div class="clearfix"></div>
        <button
        type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal"
        data-foto="{{asset('storage/formatur/'.$f->image)}}"
        data-nama="{{ $f->nama }}"
        data-nim="{{ $f->nim }}"
        data-ttl="{{ $f->ttl }}"
        data-jurusan="{{ $f->jurusan }}"
        data-visi="{{ $f->visi }}"
        >Detail</button>
        <br>
      </div>
      @endforeach
      <div class="clearfix"></div>
      <div></div>
      <div><input class="btn btn-success" type="submit" name="Vote" value="Vote"></div>
      </form>
      @else
      <div>
        <p>Belum ditemukan Calon Formatur</p>
      </div>
      @endif

   @include('formatur-detail')
  </div>
</div><br>
@endsection

resources/views/vote/login-peserta.blade.php
@extends('layouts.votelayout')

@section('content')
<div class="container text-center">    
  <h3>Silakan Masukkan ID Peserta</h3>
  <div class="row">
    <form method="POST" action="{{route('login-peserta.store')}}">
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      <div class="col-sm-4 col-md-4 col-lg-4"></div>
      <div class="col-sm-4 col-md-4 col-lg-4 form-group">
      	
      	<label>ID Peserta</label><input type="text" name="user" class="form-control">



      </div>
      <div class="col-sm-4 col-md-4 col-lg-4"></div>
      
      <div class="clearfix"></div>
      
      <div><input class="btn btn-success" type="submit" name="Masuk" value="Masuk"></div>
      </form>
    
  </div>
</div><br>
@endsection

resources/views/vote/sukses.blade.php
@extends('layouts.votelayout')
@section('content')
<div class="container text-center" style="margin-top: 50px">    
  <h3>Sukses Gan</h3>
  <a href="{{ url('/vote')}}">Kembali</a>
  </div>
</div><br>
@endsection