routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');

});
Route::get('hasil','VoteController@hasil');
Route::view('about','about');
Route::resource('vote','VoteController');


Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');
Route::resource('/admin/peserta', 'PesertaController',['as'=>'admin']);
Route::resource('/admin/formatur', 'FormaturController',['as'=>'admin']);
Route::get('swal/{type}', 'HomeController@myNotification');

app/Formatur.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Formatur extends Model
{
    
}

app/Http/Controllers/FormaturController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Formatur;

class FormaturController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $arr['formatur'] = Formatur::all();
        return view('admin.formatur.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.formatur.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Formatur $formatur)
    {
        if (isset($request->image) && $request->image->getClientOriginalName()) {
            $ext = $request->image->getClientOriginalExtension();
            $file = date('YmdHis').rand(1,99999).'.'.$ext;
            $request->image->storeAs('public/formatur',$file);
        }
        else
        {
            $file = '';
        }
        if ($request->nama != '' and $request->panggilan != '' and $request->nim != '' and $request->jurusan != '' and $request->visi != '') {
            $formatur->nama = $request->nama;
            $formatur->panggilan = $request->panggilan;
            $formatur->nim = $request->nim;
            $formatur->ttl = $request->ttl;
            $formatur->jurusan = $request->jurusan;
            $formatur->visi = $request->visi;
            $formatur->image = $file;
            $formatur->save();
            alert()->success('Data Berhasil  Ditambahkan')->persistent('OK');
            return back();
        }else
        {
            alert()->error('Silakan Periksa data anda yang anda Masukkan','Gagal Menambahkan Data')->persistent('ok');
            return back();
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Formatur $formatur)
    {
        $arr['formatur'] = $formatur;
        return view('admin.formatur.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Formatur $formatur)
    {
        if (isset($request->image) && $request->image->getClientOriginalName()) {
            $ext = $request->image->getClientOriginalExtension();
            $file = date('YmdHis').rand(1,99999).'.'.$ext;
            $request->image->storeAs('public/formatur',$file);
        }
        else
        {
            if (!$formatur->image)
                $file = '';
            else
                $file = $formatur->image;

        }

        if ($request->nama != '' and $request->panggilan != '' and $request->nim != '' and $request->jurusan != '' and $request->visi != '') {
            $formatur->nama = $request->nama;
            $formatur->panggilan = $request->panggilan;
            $formatur->nim = $request->nim;
            $formatur->ttl = $request->ttl;
            $formatur->jurusan = $request->jurusan;
            $formatur->visi = $request->visi;
            $formatur->image = $file;
            $formatur->save();
            alert()->success('Data Berhasil Perbaharui')->persistent('OK');
            return back();
        }else
        {
            alert()->error('Silakan Periksa data anda yang anda Masukkan','Gagal Menambahkan Data')->persistent('ok');
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/formatur/create.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Dashboard
  </h1>
  
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home </a></li>
    <li class="active">Add News</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<form method="POST" action="{{ route('admin.formatur.store') }}" enctype="multipart/form-data" >
		<input type="hidden" name="_token" value="{{ csrf_token() }}">

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Foto</label>
				<div class="col-md-6"><input type="file" name="image"></div>
				<div class="clearfix"></div>
			</div>
		</div>		

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Nama Lengkap</label>
				<div class="col-md-6"><input type="text" name="nama" class="form-control"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Nama Panggilan</label>
				<div class="col-md-6"><input type="text" name="panggilan" class="form-control"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">NIM</label>
				<div class="col-md-6"><input type="text" name="nim" class="form-control"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Tempat Tanggal Lahir</label>
				<div class="col-md-6"><input type="text" name="ttl" class="form-control"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Jurusan</label>
				<div class="col-md-6"><input type="text" name="jurusan" class="form-control"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Visi</label>
				<div class="col-md-6"><textarea name="visi" class="form-control"></textarea></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<input type="submit" name="" class="btn btn-info" value="Save">
		</div>
	</form>
</section>


@endsection

resources/views/admin/formatur/edit.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Dashboard
  </h1>
  
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home </a></li>
    <li class="active">Add News</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<form method="POST" action="{{ route('admin.formatur.update',$formatur->id) }}" enctype="multipart/form-data" >
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		@method('PUT')
		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Foto</label>
				<div class="col-md-6"><input type="file" name="image"></div>
				@if($formatur->image)
				<div class="col-md-9">
					<img src="{{ asset('storage/formatur/'.$formatur->image) }}" style="width: 150px">
				</div>
				@endif
				<div class="clearfix"></div>
			</div>
		</div>		

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Nama Lengkap</label>
				<div class="col-md-6"><input type="text" name="nama" class="form-control" value="{{ $formatur->nama }}"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Nama Panggilan</label>
				<div class="col-md-6"><input type="text" name="panggilan" class="form-control" value="{{ $formatur->panggilan }}"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">NIM</label>
				<div class="col-md-6"><input type="text" name="nim" class="form-control" value="{{ $formatur->nim }}"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Tempat Tanggal Lahir</label>
				<div class="col-md-6"><input type="text" name="ttl" class="form-control" value="{{ $formatur->ttl }}"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Jurusan</label>
				<div class="col-md-6"><input type="text" name="jurusan" class="form-control" value="{{ $formatur->jurusan }}"></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<div class="row">
				<label class="col-md-3">Visi</label>
				<div class="col-md-6"><textarea name="visi" class="form-control">{{ $formatur->visi }}</textarea></div>
				<div class="clearfix"></div>
			</div>
		</div>

		<div class="form-group">
			<input type="submit" name="" class="btn btn-info" value="Save"> <a href="{{route('admin.formatur.index')}}" class="btn btn-info">Kembali</a>
		</div>
	</form>
</section>


@endsection

resources/views/admin/formatur/index.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Dashboard
  </h1>
  
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home </a></li>
    <li class="active">Formatur</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <p>
    <a href="{{ route('admin.formatur.create') }}" class="btn btn-primary">Tambah Formatur</a>
  </p>
  <p>Jumlah Formatur Terdaftar Saat Ini Adalah {{count($formatur)}} Formatur</p>
  <table class="table table-bordered table-striped">
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Action</th>
    </tr>
    @if(count($formatur))
    @foreach ($formatur as $f)
      <tr>
        <td>{{$f->id}}</td>
        <td>{{$f->nama}}</td>
        <td><a href="{{ route('admin.formatur.edit',$f->id) }}" class="btn btn-info">Edit</a> 
          <a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-danger">Delete</a>
          <form method="post" action="{{ route('admin.formatur.destroy',$f->id)}}">
            @method('DELETE')
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
          </form>
        </td>
      </tr>
    @endforeach
    @else
    <tr><td colspan="3">Tidak Ditemukan Calon Formatur</td></tr>
    @endif
  </table>
  
</section>


@endsection