routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');

});
Route::get('hasil','VoteController@hasil');
Route::view('about','about');
Route::resource('vote','VoteController');


Auth::routes();

Route::get('/admin', 'HomeController@index')->name('home');
Route::resource('/admin/peserta', 'PesertaController',['as'=>'admin']);
Route::resource('/admin/formatur', 'FormaturController',['as'=>'admin']);
Route::get('swal/{type}', 'HomeController@myNotification');

app/Peserta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Peserta extends Model
{
    protected $table = 'pesertas';
    protected $primaryKey = 'user_id';
    public $incrementing = false;

    public function votes ()
    {
    	return $this->belongsToMany('App\Vote', 'namatable ini', 'id ini', 'id di vote');
    }
    
}

app/Http/Controllers/PesertaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Peserta;
use Alert;

class PesertaController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $arr['peserta'] = DB::table('pesertas')
                ->selectRaw('pesertas.user_id,(select count(*) from votes where user_id=pesertas.user_id) jumlah')
                ->orderByRaw('created_at desc')
                ->paginate(6);
        
        // $arr['peserta']= Peserta::orderBy('created_at','desc')->paginate(6);
        $arr['total']=Peserta::all();
        // $arr['peserta']=Peserta::all();
        // $arr['peserta'] = DB::table('peserta')->orderBy('created_at','desc')->get();
        return view('admin.peserta.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        // return view('admin.peserta.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Peserta $peserta)
    {
        
        
        
        $id = 'musy10'.str_random(6);

        $peserta->user_id = $id;
        $peserta->save();
        alert()->success($id,'Berikut Adalah ID Peserta')->persistent('Done');
        return redirect()->route('admin.peserta.index');
        
        
        
        // return redirect()->route('admin.peserta.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        DB::table('pesertas')->where('user_id',$id)->delete();
        alert()->success($id,'Berhasil Menghapus ID Peserta')->persistent('Done');
        return redirect()->route('admin.peserta.index');
    }
}

resources/views/admin/peserta/create.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Dashboard
  </h1>
  
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home </a></li>
    <li class="active">Peserta</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <p>
    <a href="" class="btn btn-primary">Klik Generate</a>
  </p>
</section>


@endsection

resources/views/admin/peserta/index.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    ID PESERTA MUSYAWARAH KERJA
  </h1>
  
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home </a></li>
    <li class="active">Peserta</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <form method="POST" action="{{ route('admin.peserta.store') }}">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <div class="form-group">
      <div class="row">
        <label class="col-md-1">Contoh ID</label>
        <b><input class="col-md-2" type="text" name="title" class="form-control" value="{{'musy10'.str_random(6)}}" disabled></b>
        <div class="clearfix"></div>
      </div>
    </div>
    <div class="form-group">
      <input type="submit"  class="btn btn-info" value="TAMBAH ID">
    </div>
  </form>
  <div class="clearfix"></div>
  <label>Jumlah ID Peserta Saat Ini : {{count($total)}}</label>
  <div class="clearfix"></div>
  <table id="data" class="table table-bordered table-striped">
    <tr>
      <th class="col-md-4">ID</th>
      <th class="col-md-4">Status</th>
      <th class="col-md-4">Action</th>
    </tr>
    @if(count($peserta))
    @foreach ($peserta as $p)
      <tr>
        <td>{{ $p->user_id }}</td>
        <td>
          @if($p->jumlah == 13)
          <label class="btn btn-success btn-sm">Sudah memilih</label>
          @elseif($p->jumlah > 13)
          <label class="btn btn-danger btn-sm">Lebih 13</label>
          @else
          <label class="btn btn-warning btn-sm">Belum Memilih</label>
          @endif
          </td>
        <td><a href="javascript:void(0)" class="btn btn-info" disabled>Edit</a> 
          <a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-danger">Delete</a>
          <form method="post" action="{{ route('admin.peserta.destroy',$p->user_id)}}">
            @method('DELETE')
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
          </form>
        </td>
      </tr>
    @endforeach
    @else
    <tr><td colspan="3">Belum ada ID Peserta</td></tr>
    @endif
  </table>

</section>




@endsection